config/routes.rb
NrdTraining::Application.routes.draw do
  resources :trades

  resources :training_days

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/trade.rb
class Trade < ActiveRecord::Base
end

app/models/training_day.rb
class TrainingDay < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "Access denied."
    redirect_to (request.referrer || root_path)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  before_action :set_trade, only: [:show, :edit, :update, :destroy]

  # GET /trades
  # GET /trades.json
  def index
    @trades = Trade.all
  end

  # GET /trades/1
  # GET /trades/1.json
  def show
  end

  # GET /trades/new
  def new
    @trade = Trade.new
  end

  # GET /trades/1/edit
  def edit
  end

  # POST /trades
  # POST /trades.json
  def create
    @trade = Trade.new(trade_params)

    respond_to do |format|
      if @trade.save
        format.html { redirect_to @trade, notice: 'Trade was successfully created.' }
        format.json { render action: 'show', status: :created, location: @trade }
      else
        format.html { render action: 'new' }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trades/1
  # PATCH/PUT /trades/1.json
  def update
    respond_to do |format|
      if @trade.update(trade_params)
        format.html { redirect_to @trade, notice: 'Trade was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @trade }
      else
        format.html { render action: 'edit' }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trades/1
  # DELETE /trades/1.json
  def destroy
    @trade.destroy
    respond_to do |format|
      format.html { redirect_to trades_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trade
      @trade = Trade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trade_params
      params.require(:trade).permit(:name, :mosid)
    end
end

app/controllers/training_days_controller.rb
class TrainingDaysController < ApplicationController
  before_action :set_training_day, only: [:show, :edit, :update, :destroy]

  # GET /training_days
  # GET /training_days.json
  def index
    @training_days = TrainingDay.all
  end

  # GET /training_days/1
  # GET /training_days/1.json
  def show
  end

  # GET /training_days/new
  def new
    @training_day = TrainingDay.new
  end

  # GET /training_days/1/edit
  def edit
  end

  # POST /training_days
  # POST /training_days.json
  def create
    @training_day = TrainingDay.new(training_day_params)

    respond_to do |format|
      if @training_day.save
        format.html { redirect_to @training_day, notice: 'Training day was successfully created.' }
        format.json { render action: 'show', status: :created, location: @training_day }
      else
        format.html { render action: 'new' }
        format.json { render json: @training_day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /training_days/1
  # PATCH/PUT /training_days/1.json
  def update
    respond_to do |format|
      if @training_day.update(training_day_params)
        format.html { redirect_to @training_day, notice: 'Training day was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @training_day }
      else
        format.html { render action: 'edit' }
        format.json { render json: @training_day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /training_days/1
  # DELETE /training_days/1.json
  def destroy
    @training_day.destroy
    respond_to do |format|
      format.html { redirect_to training_days_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_training_day
      @training_day = TrainingDay.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def training_day_params
      params.require(:training_day).permit(:date, :details)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized, except: [:show]

  def index
    @users = User.all
    authorize @users
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to root_path, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/helpers/training_days_helper.rb
module TrainingDaysHelper
end

app/views/home/index.html.erb
<h3>Home</h3>
<div class="row-fluid">
  <div class="col-md-6">
    <div class="well">
      <h1>Schedule by Training Day</h1>
      <p>To view the entire training schedule by date</p>
      <p>
        <a class="btn btn-primary btn-large" <%= link_to 'Training Days', training_days_path %></a>
      </p>
    </div>
  </div>
  <div class="col-md-6">
    <div class="well">
      <h1>Schedule by Trade</h1>
      <p>To view the training schedule by trade</p>
      <p>
        <a class="btn btn-primary btn-large" <%= link_to 'Trade', training_days_path %></a>
      </p>
    </div>
  </div>
</div>
<% if !current_user.nil? and current_user.admin? %>
  <% @users.each do |user| %>
    <p>User: <%=link_to user.email, user %> Role: <%= user.role unless user.role.nil? %></p>
  <% end %>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
<% else %>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Nrd Training" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Nrd Training" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/trades/_form.html.erb
<%= form_for(@trade) do |f| %>
  <% if @trade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trade.errors.count, "error") %> prohibited this trade from being saved:</h2>

      <ul>
      <% @trade.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :mosid %><br>
    <%= f.number_field :mosid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trades/edit.html.erb
<h1>Editing trade</h1>

<%= render 'form' %>

<%= link_to 'Show', @trade %> |
<%= link_to 'Back', trades_path %>

app/views/trades/index.html.erb
<h1>Listing trades</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Mosid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trades.each do |trade| %>
      <tr>
        <td><%= trade.name %></td>
        <td><%= trade.mosid %></td>
        <td><%= link_to 'Show', trade %></td>
        <td><%= link_to 'Edit', edit_trade_path(trade) %></td>
        <td><%= link_to 'Destroy', trade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trade', new_trade_path %>

app/views/trades/new.html.erb
<h1>New trade</h1>

<%= render 'form' %>

<%= link_to 'Back', trades_path %>

app/views/trades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @trade.name %>
</p>

<p>
  <strong>Mosid:</strong>
  <%= @trade.mosid %>
</p>

<%= link_to 'Edit', edit_trade_path(@trade) %> |
<%= link_to 'Back', trades_path %>

app/views/training_days/_form.html.erb
<%= form_for(@training_day) do |f| %>
  <% if @training_day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@training_day.errors.count, "error") %> prohibited this training_day from being saved:</h2>

      <ul>
      <% @training_day.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_area :details %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/training_days/edit.html.erb
<h1>Editing training_day</h1>

<%= render 'form' %>

<%= link_to 'Show', @training_day %> |
<%= link_to 'Back', training_days_path %>

app/views/training_days/index.html.erb
<h1>Listing training_days</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Details</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @training_days.each do |training_day| %>
      <tr>
        <td><%= training_day.date %></td>
        <td><%= training_day.details %></td>
        <td><%= link_to 'Show', training_day %></td>
        <td><%= link_to 'Edit', edit_training_day_path(training_day) %></td>
        <td><%= link_to 'Destroy', training_day, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Training day', new_training_day_path %>

app/views/training_days/new.html.erb
<h1>New training_day</h1>

<%= render 'form' %>

<%= link_to 'Back', training_days_path %>

app/views/training_days/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @training_day.date %>
</p>

<p>
  <strong>Details:</strong>
  <%= @training_day.details %>
</p>

<%= link_to 'Edit', edit_training_day_path(@training_day) %> |
<%= link_to 'Back', training_days_path %>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Email: <%= @user.email if @user.email %></p>